bertrand: 
        repository: ${PATH_EPYTOPE}/../external/bertrand
        conda: epytope
imrex: 
        conda: deepTCR
ergo-ii: 
        repository: ${PATH_EPYTOPE}/../external/ERGO-II
        conda: epytope_torch21
ergo-i: 
        repository: ${PATH_EPYTOPE}/../external/ERGO
        conda: epytope_torch21
titan: 
        conda: epytope_torch11_1
teinet: 
        repository: ${PATH_EPYTOPE}/../external/TEINet
        conda: epytope_torch11
epitcr: 
        repository: ${PATH_EPYTOPE}/../external/epiTCR
        conda: epytope
atm-tcr: 
        repository: ${PATH_EPYTOPE}/../external/ATM-TCR
        conda: epytope_torch11
        cuda: True
dlptcr: 
        repository: ${PATH_EPYTOPE}/../external/DLpTCR
        conda: epytope
pmtnet: 
        repository: ${PATH_EPYTOPE}/../external/pMTnet
        conda: epytope_torch21
attntap: 
        repository: ${PATH_EPYTOPE}/../external/AttnTAP
        conda: epytope
teim: 
        repository: ${PATH_EPYTOPE}/../external/TEIM
        conda: epytope
panpep:
        repository: ${PATH_EPYTOPE}/../external/PanPep
        conda: epytope_torch11
stapler: 
        conda: epytope_stapler
tcellmatch:
        conda: epytope_numpy195
nettcr:
        repository: ${PATH_EPYTOPE}/../external/NetTCR-2.2
        conda: epytope_torch21
itcep:
        repository: ${PATH_EPYTOPE}/../external/iTCep
        conda: epytope_torch21 
tulip-tcr:
        repository: ${PATH_EPYTOPE}/../external/TULIP-TCR
        conda: epytope
